name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/laravel-dhammapada-api || git clone https://github.com/${{ github.repository }}.git /var/www/laravel-dhammapada-api
            cd /var/www/laravel-dhammapada-api

            chmod +x ./scripts/deploy.sh

            ./scripts/deploy.sh
